# Generated by Django 3.0.2 on 2020-01-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0004_uploadedimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='description',
            field=models.TextField(default='', verbose_name='Description of the uploaded image'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='title',
            field=models.CharField(default='Unknown Picture', max_length=255, verbose_name='Title of the uploaded image'),
        ),
    ]
