# Generated by Django 3.0.2 on 2020-01-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0005_auto_20200119_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='img',
            field=models.URLField(default=''),
        ),
    ]
