# Generated by Django 3.0.2 on 2020-01-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0006_uploadedimage_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='img',
        ),
    ]
